"""

Revision ID: 17a8c34d331e
Revises: 988116ea0bb1
Create Date: 2024-05-11 13:40:06.548886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a8c34d331e'
down_revision = '988116ea0bb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'dimming_events',
        sa.Column('dimming_profile_id', sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None,
        'dimming_events',
        'dimming_profiles',
        ['dimming_profile_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dimming_events', type_='foreignkey')
    op.drop_column('dimming_events', 'dimming_profile_id')
    # ### end Alembic commands ###
