"""

Revision ID: 988116ea0bb1
Revises: a2ff71067aa4
Create Date: 2024-05-11 11:00:02.254083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988116ea0bb1'
down_revision = 'a2ff71067aa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'dimming_profiles',
        sa.Column('multicast_group_id', sa.String(), nullable=False),
    )
    op.add_column(
        'dimming_profiles', sa.Column('active', sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimming_profiles', 'active')
    op.drop_column('dimming_profiles', 'multicast_group_id')
    # ### end Alembic commands ###
