"""

Revision ID: a2ff71067aa4
Revises: 6fa954d3f902
Create Date: 2024-05-03 17:40:08.928981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ff71067aa4'
down_revision = '6fa954d3f902'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'streetlamp_alarms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('time', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'atype',
            sa.Enum(
                'INVALID_VALUE',
                'OVER_VOLTAGE',
                'OVER_CURRENT',
                'OVER_POWER',
                'OVER_ENERGY',
                'OVER_FREQUENCY',
                name='alarmtype',
            ),
            nullable=False,
        ),
        sa.Column(
            'severity',
            sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='alarmseverity'),
            nullable=False,
        ),
        sa.Column('cleared', sa.Boolean(), nullable=False),
        sa.Column('dev_eui', sa.String(), nullable=False),
        sa.Column('dev_voltage', sa.Float(), nullable=False),
        sa.Column('dev_current', sa.Float(), nullable=False),
        sa.Column('dev_energy_out', sa.Float(), nullable=False),
        sa.Column('dev_energy_in', sa.Float(), nullable=False),
        sa.Column('dev_power', sa.Float(), nullable=False),
        sa.Column('dev_frequency', sa.Float(), nullable=False),
        sa.Column('dev_status_on', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_streetlamp_alarms_time'),
        'streetlamp_alarms',
        ['time'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_streetlamp_alarms_time'), table_name='streetlamp_alarms'
    )
    op.drop_table('streetlamp_alarms')
    # ### end Alembic commands ###
